project:
  type: book

book:
  title: "Het Genesisboek"
  subtitle: "Het verhaal van de mensen en projecten die Bitcoin inspirerden"
  author: "Aaron van Wirdum"
  translator: Theo Hague
  date: "2024-09-12"
  cover-image: cover.png
  isbn: 978-3-16-123450-0
  license: CC-BY-4.0
  language: nl
  original-title: "The Genesis Book"
  publisher: Konsensus Network
  navbar:
    logo: cover.png
    logo-alt: Cover
    right:
      - icon: github
        href: https://github.com/konsensusnetwork/TGB_NL
        aria-label: GitHub
      - icon: shop
        href: https://bitcoinbook.shop/
        aria-label: Shop
  page-footer:
    center:
      - text: "License"
        href: index.qmd
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - chapters/CH00.qmd
    - part: "Deel I: Grondslagen"
      chapters:
      - chapters/CH01.qmd
      - chapters/CH02.qmd
      - chapters/CH03.qmd
      - chapters/CH04.qmd
      - chapters/CH05.qmd
      - chapters/CH06.qmd
      - chapters/CH07.qmd
    - part: "Deel II: Cypherpunks"
      chapters:
      - chapters/CH08.qmd
      - chapters/CH09.qmd
      - chapters/CH10.qmd
      - chapters/CH11.qmd
      - chapters/CH12.qmd
      - chapters/CH13.qmd
    - part: "Deel III: Bitcoin"
      chapters:
      - chapters/CH14.qmd
      - chapters/CH15.qmd
      - chapters/CH16.qmd
    - chapters/CHXX.qmd
    - chapters/CHYY.qmd

format:
  html:
    theme: cosmo
    number-depth: 1
  latex:
    documentclass: memoir
    classoption: smalldemyvopaper,11pt,twoside,onecolumn,openright,extrafontsizes
    papersize: a5
  epub:
    toc: true
    toc-depth: 1
    toc-title: Inhoud
    creator: Konsensus Network
    lang: "nl-NL"